# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/break1/Data/Projects/ChelnokSklad/App/TransporterManager/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AM_MainWindow(object):
    def setupUi(self, AM_MainWindow):
        AM_MainWindow.setObjectName("AM_MainWindow")
        AM_MainWindow.resize(1021, 851)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AM_MainWindow.sizePolicy().hasHeightForWidth())
        AM_MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(AM_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 937, 623))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tvAgents = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvAgents.sizePolicy().hasHeightForWidth())
        self.tvAgents.setSizePolicy(sizePolicy)
        self.tvAgents.setMinimumSize(QtCore.QSize(0, 0))
        self.tvAgents.setStyleSheet("QTableView::item:focus { border : 2px solid blue; }")
        self.tvAgents.setAlternatingRowColors(True)
        self.tvAgents.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvAgents.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvAgents.setObjectName("tvAgents")
        self.tvAgents.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tvAgents)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        AM_MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AM_MainWindow)
        self.statusbar.setObjectName("statusbar")
        AM_MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(AM_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 27))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        AM_MainWindow.setMenuBar(self.menubar)
        self.dkObjectWdiget = QtWidgets.QDockWidget(AM_MainWindow)
        self.dkObjectWdiget.setMinimumSize(QtCore.QSize(76, 41))
        self.dkObjectWdiget.setFloating(False)
        self.dkObjectWdiget.setObjectName("dkObjectWdiget")
        self.dkObjectWdiget_Contents = QtWidgets.QWidget()
        self.dkObjectWdiget_Contents.setObjectName("dkObjectWdiget_Contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dkObjectWdiget_Contents)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dkObjectWdiget.setWidget(self.dkObjectWdiget_Contents)
        AM_MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dkObjectWdiget)
        self.dkAgent_CMD_Log = QtWidgets.QDockWidget(AM_MainWindow)
        self.dkAgent_CMD_Log.setMinimumSize(QtCore.QSize(76, 41))
        self.dkAgent_CMD_Log.setObjectName("dkAgent_CMD_Log")
        self.dkAgent_CMD_Log_Contents = QtWidgets.QWidget()
        self.dkAgent_CMD_Log_Contents.setObjectName("dkAgent_CMD_Log_Contents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dkAgent_CMD_Log_Contents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dkAgent_CMD_Log.setWidget(self.dkAgent_CMD_Log_Contents)
        AM_MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dkAgent_CMD_Log)
        self.dkButtons = QtWidgets.QDockWidget(AM_MainWindow)
        self.dkButtons.setAllowedAreas(QtCore.Qt.TopDockWidgetArea)
        self.dkButtons.setObjectName("dkButtons")
        self.dkButtons_Contents = QtWidgets.QWidget()
        self.dkButtons_Contents.setObjectName("dkButtons_Contents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dkButtons_Contents)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSimpleAgent_Test = QtWidgets.QPushButton(self.dkButtons_Contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSimpleAgent_Test.sizePolicy().hasHeightForWidth())
        self.btnSimpleAgent_Test.setSizePolicy(sizePolicy)
        self.btnSimpleAgent_Test.setStyleSheet("  QPushButton {\n"
"      background-color: rgb(114, 159, 207);\n"
"  }\n"
"\n"
"  QPushButton:checked {\n"
"    border:3px solid red;\n"
" border-radius:5px\n"
"}")
        self.btnSimpleAgent_Test.setCheckable(True)
        self.btnSimpleAgent_Test.setObjectName("btnSimpleAgent_Test")
        self.horizontalLayout.addWidget(self.btnSimpleAgent_Test)
        self.btnSimpleBox_Test = QtWidgets.QPushButton(self.dkButtons_Contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSimpleBox_Test.sizePolicy().hasHeightForWidth())
        self.btnSimpleBox_Test.setSizePolicy(sizePolicy)
        self.btnSimpleBox_Test.setStyleSheet("  QPushButton {\n"
"      background-color: rgb(114, 159, 207);\n"
"  }\n"
"\n"
"  QPushButton:checked {\n"
"    border:3px solid red;\n"
" border-radius:5px\n"
"}")
        self.btnSimpleBox_Test.setCheckable(True)
        self.btnSimpleBox_Test.setObjectName("btnSimpleBox_Test")
        self.horizontalLayout.addWidget(self.btnSimpleBox_Test)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAddAgent = QtWidgets.QPushButton(self.dkButtons_Contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddAgent.sizePolicy().hasHeightForWidth())
        self.btnAddAgent.setSizePolicy(sizePolicy)
        self.btnAddAgent.setStyleSheet("background-color: lightGreen;")
        self.btnAddAgent.setObjectName("btnAddAgent")
        self.horizontalLayout_2.addWidget(self.btnAddAgent)
        self.btnDelAgent = QtWidgets.QPushButton(self.dkButtons_Contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelAgent.sizePolicy().hasHeightForWidth())
        self.btnDelAgent.setSizePolicy(sizePolicy)
        self.btnDelAgent.setStyleSheet("background-color: red;")
        self.btnDelAgent.setObjectName("btnDelAgent")
        self.horizontalLayout_2.addWidget(self.btnDelAgent)
        self.btnDisconnect = QtWidgets.QPushButton(self.dkButtons_Contents)
        self.btnDisconnect.setStyleSheet("background-color: red;")
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.horizontalLayout_2.addWidget(self.btnDisconnect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnChargeOff = QtWidgets.QPushButton(self.dkButtons_Contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnChargeOff.sizePolicy().hasHeightForWidth())
        self.btnChargeOff.setSizePolicy(sizePolicy)
        self.btnChargeOff.setObjectName("btnChargeOff")
        self.horizontalLayout_3.addWidget(self.btnChargeOff)
        self.btnChargeOn = QtWidgets.QPushButton(self.dkButtons_Contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnChargeOn.sizePolicy().hasHeightForWidth())
        self.btnChargeOn.setSizePolicy(sizePolicy)
        self.btnChargeOn.setObjectName("btnChargeOn")
        self.horizontalLayout_3.addWidget(self.btnChargeOn)
        self.leChargePort = QtWidgets.QLineEdit(self.dkButtons_Contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leChargePort.sizePolicy().hasHeightForWidth())
        self.leChargePort.setSizePolicy(sizePolicy)
        self.leChargePort.setObjectName("leChargePort")
        self.horizontalLayout_3.addWidget(self.leChargePort)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.dkButtons.setWidget(self.dkButtons_Contents)
        AM_MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dkButtons)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(AM_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(AM_MainWindow)

    def retranslateUi(self, AM_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        AM_MainWindow.setWindowTitle(_translate("AM_MainWindow", "AgentsManager"))
        self.menuFile.setTitle(_translate("AM_MainWindow", "File"))
        self.dkObjectWdiget.setWindowTitle(_translate("AM_MainWindow", "Object Wdiget"))
        self.dkAgent_CMD_Log.setWindowTitle(_translate("AM_MainWindow", "Agent_CMD_Log"))
        self.dkButtons.setWindowTitle(_translate("AM_MainWindow", "Action Buttons"))
        self.btnSimpleAgent_Test.setText(_translate("AM_MainWindow", "Simple Agent Test"))
        self.btnSimpleBox_Test.setText(_translate("AM_MainWindow", "Simple Box Test"))
        self.btnAddAgent.setText(_translate("AM_MainWindow", "Add Agent"))
        self.btnAddAgent.setShortcut(_translate("AM_MainWindow", "Ins"))
        self.btnDelAgent.setText(_translate("AM_MainWindow", "Del Agent"))
        self.btnDelAgent.setShortcut(_translate("AM_MainWindow", "Del"))
        self.btnDisconnect.setText(_translate("AM_MainWindow", "Disconnect"))
        self.btnChargeOff.setText(_translate("AM_MainWindow", "Charge Off"))
        self.btnChargeOn.setText(_translate("AM_MainWindow", "Charge On"))
        self.leChargePort.setText(_translate("AM_MainWindow", "ttyS0"))

