# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/easyrid3r/Projects/chelnoksklad/StorageMapDesigner/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SMD_MainWindow(object):
    def setupUi(self, SMD_MainWindow):
        SMD_MainWindow.setObjectName("SMD_MainWindow")
        SMD_MainWindow.resize(1180, 851)
        self.centralwidget = QtWidgets.QWidget(SMD_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StorageMap_View = QtWidgets.QGraphicsView(self.centralwidget)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.StorageMap_View.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.StorageMap_View.setForegroundBrush(brush)
        self.StorageMap_View.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
        self.StorageMap_View.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.StorageMap_View.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.StorageMap_View.setObjectName("StorageMap_View")
        self.horizontalLayout.addWidget(self.StorageMap_View)
        SMD_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SMD_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuGraph_Edit = QtWidgets.QMenu(self.menubar)
        self.menuGraph_Edit.setObjectName("menuGraph_Edit")
        SMD_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SMD_MainWindow)
        self.statusbar.setObjectName("statusbar")
        SMD_MainWindow.setStatusBar(self.statusbar)
        self.toolMain = QtWidgets.QToolBar(SMD_MainWindow)
        self.toolMain.setOrientation(QtCore.Qt.Horizontal)
        self.toolMain.setObjectName("toolMain")
        SMD_MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolMain)
        self.toolEdit = QtWidgets.QToolBar(SMD_MainWindow)
        self.toolEdit.setOrientation(QtCore.Qt.Horizontal)
        self.toolEdit.setObjectName("toolEdit")
        SMD_MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolEdit)
        self.dkObjectProps = QtWidgets.QDockWidget(SMD_MainWindow)
        self.dkObjectProps.setObjectName("dkObjectProps")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tvObjectProps = QtWidgets.QTableView(self.dockWidgetContents)
        self.tvObjectProps.setMinimumSize(QtCore.QSize(325, 0))
        self.tvObjectProps.setStyleSheet("QTableView::item:focus\n"
"{\n"
"border : 2px solid blue;\n"
"/*color: white;*/\n"
"/*selection-color: black;\n"
"selection-background-color: red;*/\n"
"}\n"
"")
        self.tvObjectProps.setAlternatingRowColors(True)
        self.tvObjectProps.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvObjectProps.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvObjectProps.setObjectName("tvObjectProps")
        self.tvObjectProps.horizontalHeader().setStretchLastSection(True)
        self.tvObjectProps.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tvObjectProps)
        self.dkObjectProps.setWidget(self.dockWidgetContents)
        SMD_MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dkObjectProps)
        self.dkView = QtWidgets.QDockWidget(SMD_MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dkView.setFont(font)
        self.dkView.setObjectName("dkView")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.lbGridSize = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.lbGridSize.setObjectName("lbGridSize")
        self.gridLayout.addWidget(self.lbGridSize, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.sbGridSize = QtWidgets.QSpinBox(self.dockWidgetContents_2)
        self.sbGridSize.setMaximum(1000)
        self.sbGridSize.setObjectName("sbGridSize")
        self.gridLayout.addWidget(self.sbGridSize, 0, 3, 1, 1)
        self.pbGrid = QtWidgets.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbGrid.sizePolicy().hasHeightForWidth())
        self.pbGrid.setSizePolicy(sizePolicy)
        self.pbGrid.setMinimumSize(QtCore.QSize(32, 32))
        self.pbGrid.setMaximumSize(QtCore.QSize(32, 32))
        self.pbGrid.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbGrid.setIcon(icon)
        self.pbGrid.setIconSize(QtCore.QSize(32, 32))
        self.pbGrid.setCheckable(True)
        self.pbGrid.setObjectName("pbGrid")
        self.gridLayout.addWidget(self.pbGrid, 1, 0, 1, 1)
        self.pbBBox = QtWidgets.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbBBox.sizePolicy().hasHeightForWidth())
        self.pbBBox.setSizePolicy(sizePolicy)
        self.pbBBox.setMinimumSize(QtCore.QSize(32, 32))
        self.pbBBox.setMaximumSize(QtCore.QSize(32, 32))
        self.pbBBox.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/bbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbBBox.setIcon(icon1)
        self.pbBBox.setIconSize(QtCore.QSize(32, 32))
        self.pbBBox.setCheckable(True)
        self.pbBBox.setObjectName("pbBBox")
        self.gridLayout.addWidget(self.pbBBox, 1, 1, 1, 1)
        self.pbSnap = QtWidgets.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSnap.sizePolicy().hasHeightForWidth())
        self.pbSnap.setSizePolicy(sizePolicy)
        self.pbSnap.setMinimumSize(QtCore.QSize(32, 32))
        self.pbSnap.setMaximumSize(QtCore.QSize(32, 32))
        self.pbSnap.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/snap_to_grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSnap.setIcon(icon2)
        self.pbSnap.setIconSize(QtCore.QSize(32, 32))
        self.pbSnap.setCheckable(True)
        self.pbSnap.setObjectName("pbSnap")
        self.gridLayout.addWidget(self.pbSnap, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 4)
        self.dkView.setWidget(self.dockWidgetContents_2)
        SMD_MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dkView)
        self.acFitToPage = QtWidgets.QAction(SMD_MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/zoom_fit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acFitToPage.setIcon(icon3)
        self.acFitToPage.setObjectName("acFitToPage")
        self.acZoomIn = QtWidgets.QAction(SMD_MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acZoomIn.setIcon(icon4)
        self.acZoomIn.setObjectName("acZoomIn")
        self.acZoomOut = QtWidgets.QAction(SMD_MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acZoomOut.setIcon(icon5)
        self.acZoomOut.setObjectName("acZoomOut")
        self.acGrid = QtWidgets.QAction(SMD_MainWindow)
        self.acGrid.setCheckable(True)
        self.acGrid.setIcon(icon)
        self.acGrid.setObjectName("acGrid")
        self.acBBox = QtWidgets.QAction(SMD_MainWindow)
        self.acBBox.setCheckable(True)
        self.acBBox.setIcon(icon1)
        self.acBBox.setObjectName("acBBox")
        self.acLoadGraphML = QtWidgets.QAction(SMD_MainWindow)
        self.acLoadGraphML.setObjectName("acLoadGraphML")
        self.acSaveGraphML = QtWidgets.QAction(SMD_MainWindow)
        self.acSaveGraphML.setObjectName("acSaveGraphML")
        self.acAddNode = QtWidgets.QAction(SMD_MainWindow)
        self.acAddNode.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/add_node.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acAddNode.setIcon(icon6)
        self.acAddNode.setObjectName("acAddNode")
        self.acAddEdge = QtWidgets.QAction(SMD_MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/add_edge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acAddEdge.setIcon(icon7)
        self.acAddEdge.setObjectName("acAddEdge")
        self.acAddEdge_direct = QtWidgets.QAction(SMD_MainWindow)
        self.acAddEdge_direct.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/add_edge_1-2_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/images/add_edge_1-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.acAddEdge_direct.setIcon(icon8)
        self.acAddEdge_direct.setObjectName("acAddEdge_direct")
        self.acAddEdge_reverse = QtWidgets.QAction(SMD_MainWindow)
        self.acAddEdge_reverse.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/add_edge_2-1_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/images/add_edge_2-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.acAddEdge_reverse.setIcon(icon9)
        self.acAddEdge_reverse.setObjectName("acAddEdge_reverse")
        self.acDelMultiEdge = QtWidgets.QAction(SMD_MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/del_edge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acDelMultiEdge.setIcon(icon10)
        self.acDelMultiEdge.setObjectName("acDelMultiEdge")
        self.acReverseEdges = QtWidgets.QAction(SMD_MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/reverse_edge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acReverseEdges.setIcon(icon11)
        self.acReverseEdges.setObjectName("acReverseEdges")
        self.acSnapToGrid = QtWidgets.QAction(SMD_MainWindow)
        self.acSnapToGrid.setCheckable(True)
        self.acSnapToGrid.setIcon(icon2)
        self.acSnapToGrid.setObjectName("acSnapToGrid")
        self.menuFile.addAction(self.acLoadGraphML)
        self.menuFile.addAction(self.acSaveGraphML)
        self.menuView.addAction(self.acFitToPage)
        self.menuView.addAction(self.acZoomIn)
        self.menuView.addAction(self.acZoomOut)
        self.menuView.addAction(self.acGrid)
        self.menuView.addAction(self.acSnapToGrid)
        self.menuView.addAction(self.acBBox)
        self.menuGraph_Edit.addAction(self.acAddNode)
        self.menuGraph_Edit.addAction(self.acAddEdge_direct)
        self.menuGraph_Edit.addAction(self.acAddEdge_reverse)
        self.menuGraph_Edit.addAction(self.acAddEdge)
        self.menuGraph_Edit.addAction(self.acDelMultiEdge)
        self.menuGraph_Edit.addAction(self.acReverseEdges)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuGraph_Edit.menuAction())
        self.toolMain.addAction(self.acFitToPage)
        self.toolMain.addAction(self.acZoomIn)
        self.toolMain.addAction(self.acZoomOut)
        self.toolMain.addAction(self.acGrid)
        self.toolMain.addAction(self.acSnapToGrid)
        self.toolMain.addAction(self.acBBox)
        self.toolEdit.addAction(self.acAddNode)
        self.toolEdit.addAction(self.acAddEdge_direct)
        self.toolEdit.addAction(self.acAddEdge_reverse)
        self.toolEdit.addAction(self.acAddEdge)
        self.toolEdit.addAction(self.acDelMultiEdge)
        self.toolEdit.addAction(self.acReverseEdges)

        self.retranslateUi(SMD_MainWindow)
        self.pbGrid.toggled['bool'].connect(self.acGrid.trigger)
        self.pbBBox.toggled['bool'].connect(self.acBBox.trigger)
        self.pbSnap.toggled['bool'].connect(self.acSnapToGrid.trigger)
        self.acGrid.triggered['bool'].connect(self.pbGrid.setChecked)
        QtCore.QMetaObject.connectSlotsByName(SMD_MainWindow)

    def retranslateUi(self, SMD_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        SMD_MainWindow.setWindowTitle(_translate("SMD_MainWindow", "Storage Map Designer"))
        self.menuFile.setTitle(_translate("SMD_MainWindow", "File"))
        self.menuView.setTitle(_translate("SMD_MainWindow", "View"))
        self.menuGraph_Edit.setTitle(_translate("SMD_MainWindow", "Graph Edit"))
        self.toolMain.setWindowTitle(_translate("SMD_MainWindow", "Tool Bar"))
        self.toolEdit.setWindowTitle(_translate("SMD_MainWindow", "Tool Bar"))
        self.dkObjectProps.setWindowTitle(_translate("SMD_MainWindow", "Object Props"))
        self.lbGridSize.setText(_translate("SMD_MainWindow", "Grid size:"))
        self.acFitToPage.setText(_translate("SMD_MainWindow", "Fit To Page"))
        self.acFitToPage.setToolTip(_translate("SMD_MainWindow", "Fit To Page"))
        self.acFitToPage.setShortcut(_translate("SMD_MainWindow", "Ctrl+0"))
        self.acZoomIn.setText(_translate("SMD_MainWindow", "Zoom In"))
        self.acZoomIn.setToolTip(_translate("SMD_MainWindow", "Zoom In"))
        self.acZoomIn.setShortcut(_translate("SMD_MainWindow", "Ctrl++"))
        self.acZoomOut.setText(_translate("SMD_MainWindow", "Zoom Out"))
        self.acZoomOut.setToolTip(_translate("SMD_MainWindow", "Zoom Out"))
        self.acZoomOut.setShortcut(_translate("SMD_MainWindow", "Ctrl+-"))
        self.acGrid.setText(_translate("SMD_MainWindow", "Grid"))
        self.acGrid.setToolTip(_translate("SMD_MainWindow", "Grid"))
        self.acGrid.setShortcut(_translate("SMD_MainWindow", "#"))
        self.acBBox.setText(_translate("SMD_MainWindow", "BBox"))
        self.acBBox.setToolTip(_translate("SMD_MainWindow", "BBox"))
        self.acLoadGraphML.setText(_translate("SMD_MainWindow", "Load GraphML"))
        self.acLoadGraphML.setToolTip(_translate("SMD_MainWindow", "Load GraphML"))
        self.acSaveGraphML.setText(_translate("SMD_MainWindow", "Save Graph ML"))
        self.acSaveGraphML.setToolTip(_translate("SMD_MainWindow", "Save Graph ML"))
        self.acAddNode.setText(_translate("SMD_MainWindow", "Add node mode"))
        self.acAddNode.setToolTip(_translate("SMD_MainWindow", "Add node mode"))
        self.acAddEdge.setText(_translate("SMD_MainWindow", "Add edges"))
        self.acAddEdge.setToolTip(_translate("SMD_MainWindow", "Add edges for selected nodes"))
        self.acAddEdge_direct.setText(_translate("SMD_MainWindow", "Add edges direct mode"))
        self.acAddEdge_direct.setToolTip(_translate("SMD_MainWindow", "Add edges in a direct order (1 --> 2)"))
        self.acAddEdge_reverse.setText(_translate("SMD_MainWindow", "Add edges reverse mode"))
        self.acAddEdge_reverse.setToolTip(_translate("SMD_MainWindow", "Add edges in a reverse order (1 <-- 2)"))
        self.acDelMultiEdge.setText(_translate("SMD_MainWindow", "Delete multiple edge"))
        self.acDelMultiEdge.setToolTip(_translate("SMD_MainWindow", "Delete multiple edge"))
        self.acReverseEdges.setText(_translate("SMD_MainWindow", "Reverse selected edges"))
        self.acReverseEdges.setToolTip(_translate("SMD_MainWindow", "Reverse selected edges"))
        self.acSnapToGrid.setText(_translate("SMD_MainWindow", "Snap to grid"))
        self.acSnapToGrid.setToolTip(_translate("SMD_MainWindow", "Snap to grid"))

import images_rc
